/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PrintHello */

#ifndef _Included_PrintHello
#define _Included_PrintHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PrintHello
 * Method:    f
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PrintHello_f
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
